# Generated by Django 4.1.4 on 2023-11-28 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('state_number', models.CharField(max_length=9, verbose_name='Гос.номер')),
                ('stamp', models.CharField(max_length=200, verbose_name='Марка')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('status', models.CharField(max_length=200, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='CargoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Коэфициент перевозки')),
                ('comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарии')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Электронная почта')),
                ('passport', models.CharField(max_length=10, unique=True, verbose_name='Паспорт')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('login', models.CharField(max_length=20, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('client', models.BooleanField(default=False, verbose_name='Клиент')),
                ('employee', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('admin', models.BooleanField(default=False, verbose_name='Админ')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('region', models.CharField(max_length=200, verbose_name='Регион')),
            ],
        ),
        migrations.CreateModel(
            name='PointIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('warehouse_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='navigate.warehouse', verbose_name='Id склада')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарии')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес')),
                ('date_of_receipt', models.DateField(verbose_name='Дата принятия')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки в пункт выдачи')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='длина')),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='высота')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ширина')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость доставки')),
                ('status', models.CharField(max_length=200, verbose_name='Статус')),
                ('car_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='navigate.car', verbose_name='Номер Машины')),
                ('cargo_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='navigate.cargocategory', verbose_name='Категория груза')),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='navigate.user', verbose_name='Id клиента')),
                ('sending_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='navigate.pointissue', verbose_name='Адрес отправки')),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('B', models.BooleanField(default=False, verbose_name='B')),
                ('BE', models.BooleanField(default=False, verbose_name='BE')),
                ('C', models.BooleanField(default=False, verbose_name='C')),
                ('CE', models.BooleanField(default=False, verbose_name='CE')),
                ('date_of_receipt', models.DateField(verbose_name='Дата получения')),
                ('end_date', models.DateField(verbose_name='срок окончания')),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='navigate.user', verbose_name='Id сотрудника')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='driver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='navigate.user', verbose_name='Id водителя'),
        ),
    ]
